<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogRepository extends EntityRepository
{
    public function countDogs()
    {
        return $this->getEntityManager()->createQuery(
            "SELECT COUNT('id') FROM AppBundle:Dog"
        )->getOneOrNullResult();
    }
}
