<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
    public function countNotes($firstResult)
    {
        return $this->getEntityManager()->createQuery(
            "SELECT n FROM AppBundle:Note n ORDER BY n.date DESC"
        )->setMaxResults(5)
            ->setFirstResult($firstResult)
            ->getResult();
    }
}
