<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShelterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShelterRepository extends EntityRepository
{
    public function editRooms($rooms)
    {
    }
}
